### ISSUE TITLE
Error related to Google API Version v201908 disabled

### ISSUE THREAD

**Issue by adops-tcs** [kmjennison/dfp-prebid-setup#101]
New error message today.  The same scripts were working yesterday without an issue:

```

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleads/common.py", line 992, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: [ApiVersionError.UPDATE_TO_NEWER_VERSION @ version; trigger:'Version v201908 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/LenaPersonalMacBook/Desktop/Prebid_GAM_LI/dfp-prebid-setup-master-motor_v2/tasks/add_new_prebid_partner.py", line 358, in <module>
    main()
  File "/Users/LenaPersonalMacBook/Desktop/Prebid_GAM_LI/dfp-prebid-setup-master-motor_v2/tasks/add_new_prebid_partner.py", line 355, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code, line_item_format)
  File "/Users/LenaPersonalMacBook/Desktop/Prebid_GAM_LI/dfp-prebid-setup-master-motor_v2/tasks/add_new_prebid_partner.py", line 59, in setup_partner
    user_id = dfp.get_users.get_user_id_by_email(user_email)
  File "/Users/LenaPersonalMacBook/Desktop/Prebid_GAM_LI/dfp-prebid-setup-master-motor_v2/dfp/get_users.py", line 37, in get_user_id_by_email
    response = user_service.getUsersByStatement(statement.ToStatement())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleads/common.py", line 1004, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [ApiVersionError.UPDATE_TO_NEWER_VERSION @ version; trigger:'Version v201908 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.']
LenaPersonalMacBook@MacBook-Pro-4 dfp-prebid-setup-master-motor_v2 % 
```

**Comment by kmjennison** [comment]
@adops-tcs Thanks. I'll update the API version now.

**Comment by adops-tcs** [comment]
Thank you @kmjennison !
