### ISSUE TITLE
Any hints for CustomTargetingError.VALUE_NAME_EMPTY @ name issue ?

### ISSUE THREAD

**Issue by siddartha** [kmjennison/dfp-prebid-setup#115]
Hi, got a new weird issue with the CustomTargeting Key Name which are empty during the execution of the script (thank you so much for this tool). Seems similar/realted to https://github.com/kmjennison/dfp-prebid-setup/issues/76 and https://github.com/kmjennison/dfp-prebid-setup/issues/28. 

Try to debug and print some datas like descirbed here : https://github.com/kmjennison/dfp-prebid-setup/issues/28#issuecomment-310535434 . Result is I'm able to see the hb_bidder values, but not the hb_pb values and not the name of hb_bidder and hb_pb key.

I have already a Prebid configuration into my GAM account, so no creation is need. I don't think this matter for the issue but prefers to mention that these keys are already exists and filled.

`Is this correct? (y/n)
y
Found user with the given email address.
Found placement with name "Prebid".
Using existing advertiser with name "Prebid" and type "ADVERTISER".
Found an order with name "Prebid".
Using existing order with name "Prebid".
Created creative with name ": HB Prebid #1".
Created creative with name ": HB Prebid #2".
Created creative with name ": HB Prebid #3".
Created creative with name ": HB Prebid #4".
Created creative with name ": HB Prebid #5".
Created creative with name ": HB Prebid #6".
Created creative with name ": HB Prebid #7".
Created creative with name ": HB Prebid #8".
Created creative with name ": HB Prebid #9".
Created creative with name ": HB Prebid #10".
Created creative with name ": HB Prebid #11".
Created creative with name ": HB Prebid #12".
Created creative with name ": HB Prebid #13".
Created creative with name ": HB Prebid #14".
Created creative with name ": HB Prebid #15".
Created creative with name ": HB Prebid #16".
Created creative with name ": HB Prebid #17".
Created creative with name ": HB Prebid #18".
Created creative with name ": HB Prebid #19".
Created creative with name ": HB Prebid #20".
Key "hb_bidder" exists and has 18 existing values.
Key "hb_pb" exists and has 6400 existing values.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/googleads/common.py", line 984, in MakeSoapRequest
    return soap_service_method(
  File "/usr/local/lib/python3.10/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
    raise Fault(
zeep.exceptions.Fault: [CustomTargetingError.VALUE_NAME_EMPTY @ name]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 407, in <module>
    main()
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 404, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code, line_item_format, video_ad_type, vast_redirect_url)
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 90, in setup_partner
    line_items_config = create_line_item_configs(prices, order_id, placement_ids, ad_unit_ids, bidder_code, sizes,
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 194, in create_line_item_configs
    hb_bidder_value_id = HBBidderValueGetter.get_value_id(bidder_code)
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 151, in get_value_id
    val_id = self._create_value_and_return_id(value_name)
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/tasks/add_new_prebid_partner.py", line 135, in _create_value_and_return_id
    return dfp.create_custom_targeting.create_targeting_value(value_name,
  File "/Users/sid/Code/prebid/dfp-prebid-setup-master/dfp/create_custom_targeting.py", line 76, in create_targeting_value
    values = custom_targeting_service.createCustomTargetingValues(
  File "/usr/local/lib/python3.10/site-packages/googleads/common.py", line 996, in MakeSoapRequest
    raise googleads.errors.GoogleAdsServerFault(
googleads.errors.GoogleAdsServerFault: [CustomTargetingError.VALUE_NAME_EMPTY @ name]`

My settings:

`DFP_VIDEO_AD_TYPE = False
DFP_VAST_REDIRECT_URL = ''
DFP_CREATE_ADVERTISER_IF_DOES_NOT_EXIST = False
DFP_USE_EXISTING_ORDER_IF_EXISTS = True
DFP_NUM_CREATIVES_PER_LINE_ITEM = 20
DFP_CURRENCY_CODE = 'EUR'
PREBID_BIDDER_CODE = ''
PREBID_PRICE_BUCKETS = { 'precision': 2, 'min' : 0, 'max' : 1, 'increment': 0.01, }`

Any ideas how to get name or force the key name into CustomTargeting functions ?
Or am I doing something wrong? Thanks for any help/hints!

**Comment by kmjennison** [comment]
Your `PREBID_BIDDER_CODE` is an empty string, but it must be defined. This is a limitation of this package: it requires every bidder to have their own order. See: #18
