### ISSUE TITLE
python -m tasks.add_new_prebid_partner gives error

### ISSUE THREAD

**Issue by thechrise** [kmjennison/dfp-prebid-setup#21]
Traceback (most recent call last):
File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, i
n _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in
 _run_code
    exec(code, run_globals)
  File "/Users/chris/Dev/DFP/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 350, in <module>
    main()
  File "/Users/chris/Dev/DFP/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 346, in main
    num_creatives,
  File "/Users/chris/Dev/DFP/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 69, in setup_partner
    hb_bidder_key_id = get_or_create_dfp_targeting_key('hb_bidder')
  File "/Users/chris/Dev/DFP/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 150, in get_or_create_dfp_target
ing_key
    key_id = dfp.create_custom_targeting.create_targeting_key(name)
TypeError: create_targeting_key() missing 1 required positional argument: 'display_name'

**Comment by kmjennison** [comment]
Thanks, writing a fix for this now.

**Comment by kmjennison** [comment]
I wrote unit tests for this but did not test against live DFP, so let me know if you still see problems.

**Comment by thechrise** [comment]
It looks to be functioning properly. Thanks for the fix and this awesome repo!
