### ISSUE TITLE
URL Error broken pipe while creating line items 

### ISSUE THREAD

**Issue by lnishihira** [kmjennison/dfp-prebid-setup#46]
While at the "Creating line items" stage I was blocked by the following error. 
This seems it could be a timeout issue with the DFP's API,  is anyone else running into this issue? Any suggestions would be greatly appreciated. 

`Creating line items...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lilliananishihiraCheatsheet/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 364, in <module>
    main()
  File "/Users/lilliananishihiraCheatsheet/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 360, in main
    currency_code,
  File "/Users/lilliananishihiraCheatsheet/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 92, in setup_partner
    creative_ids, size_overrides=sizes)
  File "dfp/associate_line_items_and_creatives.py", line 44, in make_licas
    licas = lica_service.createLineItemCreativeAssociations(licas)
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/googleads/common.py", line 779, in MakeSoapRequest
    self._packer) for arg in args])
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/googleads/util.py", line 123, in PatchedHttpTransportSend
    fp = self.u2open(u2request)
  File "/Users/lilliananishihiraCheatsheet/Library/Python/2.7/lib/python/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 32] Broken pipe>`

**Comment by lnishihira** [comment]
I got around this by creating only 225 (half the 450 max) line items at a time. The connection does not time out this way.

I would still like to have a way to do this all at once because now this script has to be run 10+ per prebid partner.

**Comment by kmjennison** [comment]
This may have been an intermittent issue on the Ad Manager side. Closing until it arises again.
