### ISSUE TITLE
Something going wrong when implement the guid

### ISSUE THREAD

**Issue by ihoradsoperation** [kmjennison/dfp-prebid-setup#63]
Hi guys, 

I have tried to implement mentioned hack, but it doesn't work. 
I have faced with the following error (attached):

`Going to create 301 new line items.
      Order: Prebid_name
      Advertiser: name
      Owner: somename@quick-cache-221920.iam.gserviceaccount.com

    Line items will have targeting:
      hb_pb = 0.00, 0.05, 0.10, ... 14.90, 14.95, 15.00
      hb_bidder = appnexus
      placements = []

    
Is this correct? (y/n)
y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Documents/API_AD/tasks/add_new_prebid_partner.py", line 435, in <module>
    main()
  File "/Users/Documents/API_AD/tasks/add_new_prebid_partner.py", line 431, in main
    currency_code,
  File "/Users/Documents/API_AD/tasks/add_new_prebid_partner.py", line 61, in setup_partner
    user_id = dfp.get_users.get_user_id_by_email(user_email)
  File "/Users/Documents/API_AD/dfp/get_users.py", line 24, in get_user_id_by_email
    user_service = dfp_client.GetService('UserService', version='v201802')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleads/dfp.py", line 287, in GetService
    cache=self.cache)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleads/common.py", line 1125, in __init__
    endpoint, transport=transport, plugins=plugins)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/client.py", line 62, in __init__
    wsdl, self.transport, settings=self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
    document = self._get_xml_document(location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/wsdl/wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/loader.py", line 74, in load_external
    content = transport.load(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/transports.py", line 113, in load
    self.cache.add(url, content)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zeep/cache.py", line 103, in add
    cursor.execute("DELETE FROM request WHERE url = ?", (url,))
sqlite3.OperationalError: attempt to write a readonly database`

Can you support me how can I fix it?

**Comment by kmjennison** [comment]
This looks like a permissions issue related to caching. See:
https://github.com/googleads/googleads-python-lib/issues/331
https://github.com/googleads/googleads-python-lib#how-can-i-configure-or-disable-caching

Separately: please note that placements are currently required for this tool to work (see #16). The empty placement array will throw an error.
