### ISSUE TITLE
Creating line items permission denied

### ISSUE THREAD

**Issue by abdabada** [kmjennison/dfp-prebid-setup#75]
Hey guys, the script creates the order and the creatives but fails to create the line items, any idea what's happening here? 

`Using existing advertiser with name "Prebid" and type "ADVERTISER".
Found an order with name "Test Order prebid automatic script 1.4".
Using existing order with name "Test Order prebid automatic script 1.4".
Created creative with name "appnexus: HB Test Order prebid automatic script 1.4, #1".
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/googleads/common.py", line 1382, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 194, in process_reply
    return self.process_error(doc, operation)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: [PermissionError.PERMISSION_DENIED @ ]

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abdelhak.elmadkouri/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 355, in <module>
    main()
  File "/home/abdelhak.elmadkouri/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 352, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code)
  File "/home/abdelhak.elmadkouri/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 80, in setup_partner
    hb_bidder_key_id = get_or_create_dfp_targeting_key('hb_bidder')
  File "/home/abdelhak.elmadkouri/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 161, in get_or_create_dfp_targeting_key
    key_id = dfp.create_custom_targeting.create_targeting_key(name)
  File "/home/abdelhak.elmadkouri/dfp-prebid-setup/dfp/create_custom_targeting.py", line 41, in create_targeting_key
    keys = custom_targeting_service.createCustomTargetingKeys(keys)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/googleads/common.py", line 1394, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [PermissionError.PERMISSION_DENIED @ ]
`

**Comment by kmjennison** [comment]
My guess is your service account is missing some permission. Is its role set to "Trafficker" (see [docs](https://github.com/kmjennison/dfp-prebid-setup#creating-google-credentials))? If possible, can you give the role expanded permissions and try again?

**Comment by arrowak** [comment]
Was there a progress on this issue @abdabada ? I am facing the same issue. The role is Trafficker already.

**Comment by arrowak** [comment]
Hey just cracked it! The issue is not that the script is not able to create LineItems. It should be able to create LineItems, because the role "**Trafficker**" has that permission already.

The actual issue is that - at first ever run, the script will try creating "**hb_bidder**" and "**hb_pb**" keys for targeting. The "**Trafficker**" doesn't have this permission. 

So, looks like we have following options - 

1. We can give "**Administrator (AdManager Only)**" permission at first run and then change to "**Trafficker**".
2. We can manually create the required targeting keys and then run this script.

@kmjennison - Please update the documentation appropriately.

**Comment by kmjennison** [comment]
@arrowak Thanks for figuring this out! I've updated the docs.
