### ISSUE TITLE
Traffic video creatives for prebid for video

### ISSUE THREAD

**Issue by schoenbl** [kmjennison/dfp-prebid-setup#78]
I think I'm missing something obvious.

My goal is to be able to traffic video creatives for prebid for video.

I've altered the config parameter in create_creatives.py to the following:
```
  config = {
    'name': name,
    'advertiserId': advertiser_id,
    'vastRedirectType': vast,
    'vastXmlUrl': vastXml,
  }
```
When I do this, I receive an error of:
`KeyError: 'vastRedirectType'`

This is the full error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lukeschoenberger/git/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 355, in <module>
    main()
  File "/Users/lukeschoenberger/git/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 352, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code)
  File "/Users/lukeschoenberger/git/dfp-prebid-setup/tasks/add_new_prebid_partner.py", line 77, in setup_partner
    creative_ids = dfp.create_creatives.create_creatives(creative_configs)
  File "dfp/create_creatives.py", line 25, in create_creatives
    creatives = creative_service.createCreatives(creatives)
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1381, in MakeSoapRequest
    packed_args = self._PackArguments(method_name, args)
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1239, in _PackArguments
    for ((_, param), param_data) in izip(op_params, args)]
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1294, in _PackArgumentsHelper
    for item in data]
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1284, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1351, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1351, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
KeyError: 'vastRedirectType'
```

**Comment by kmjennison** [comment]
You might have to set the 'xsi_type' attribute to 'VastRedirectCreative'.

**Comment by kmjennison** [comment]
Closing in favor of #61, but feel free to keep discussing here.
