### ISSUE TITLE
Facing exception while creating line items. It created the Key value increment though

### ISSUE THREAD

**Issue by sc0rp1on** [kmjennison/dfp-prebid-setup#93]
Creating line items...
Traceback (most recent call last):
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\googleads\common.py", line 992, in MakeSoapRequest
    *packed_args, _soapheaders=soap_headers)['body']['rval']
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\zeep\proxy.py", line 45, in __call__
    kwargs,
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\zeep\wsdl\bindings\soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\zeep\wsdl\bindings\soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\zeep\wsdl\bindings\soap.py", line 287, in process_error
    detail=etree_to_string(doc),
zeep.exceptions.Fault: Unknown fault occured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\runpy.py",        line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\runpy.py",        line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sooraj\Desktop\learning\dfp\dfp-prebid-setup\tasks\add_new_preb       id_partner.py", line 358, in <module>
    main()
  File "C:\Users\sooraj\Desktop\learning\dfp\dfp-prebid-setup\tasks\add_new_preb       id_partner.py", line 355, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units,        sizes, bidder_code, prices, num_creatives, currency_code, line_item_format)
  File "C:\Users\sooraj\Desktop\learning\dfp\dfp-prebid-setup\tasks\add_new_preb       id_partner.py", line 92, in setup_partner
    line_item_ids = dfp.create_line_items.create_line_items(line_items_config)
  File "C:\Users\sooraj\Desktop\learning\dfp\dfp-prebid-setup\dfp\create_line_it       ems.py", line 18, in create_line_items
    line_items = line_item_service.createLineItems(line_items)
  File "C:\Users\sooraj\AppData\Local\Programs\Python\Python37-32\lib\site-packa       ges\googleads\common.py", line 997, in MakeSoapRequest
    '{%s}ApiExceptionFault' % self._GetBindingNamespace())
TypeError: argument should be integer or bytes-like object, not 'str'

**Comment by kmjennison** [comment]
Can you share your (non-sensitive) config values? At a glance, it looks like one of the line item settings should be an integer rather than string.

**Comment by sc0rp1on** [comment]
Placed the settings.py file here
https://gist.github.com/sc0rp1on/071d2593d7d8c036cef11e96f2f473d4

**Comment by kmjennison** [comment]
Thanks. Your config looks correct, so I don't immediately see the issue. Please make sure your local code is up to date with the latest code in this repository—if you downloaded it a while back, maybe it's related to deprecated Google Ads versions.

I'll leave this open in case others can support. If you can share a reproduction of the error or identify it by writing test, that would be helpful.

**Comment by MatthieuSTB** [comment]
Hello,

I'm having since today i think the same issue and it's related to his function :

`def _get_value_id_from_cache(self, value_name):
    val_id = None
    for value_obj in self.existing_values:
      if value_obj['name'] == value_name:
        val_id = value_obj['id']
        break
    return val_id`

Located in the 'add_new_prebid_partner.py'

Here is the console error : 

`Created a custom targeting value with name "smart" and display name "smart".
Traceback (most recent call last):
  File "C:\Users\msintobin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\msintobin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 360, in <module>
    main()
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 357, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code)
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 98, in setup_partner
    HBPBValueGetter, HBBidderRealValueGetter)
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 209, in create_line_item_configs
    hb_pb_value_id = HBPBValueGetter.get_value_id(price_str)
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 152, in get_value_id
    val_id = self._get_value_id_from_cache(value_name)
  File "C:\Users\msintobin\Google Drive\SmartAdServer\Service\TAM FR\MS\DFP\DFP-SmartPrebid-LeMonde-Prod\tasks\add_new_prebid_partner.py", line 133, in _get_value_id_from_cache
    for value_obj in self.existing_values:
TypeError: 'NoneType' object is not iterable`

Do you have any clues ?

Thanks in advance

**Comment by sc0rp1on** [comment]
I might have found the cause.
I was trying to create 2000 line items.
Just found out the limit of line items of an order is 450.
I tried creating 300 line items and it worked.

**Comment by kmjennison** [comment]
Good to know, and thanks for following up here!
