### ISSUE TITLE
Need support on this setup

### ISSUE THREAD

**Issue by u5194321** [kmjennison/dfp-prebid-setup#98]
Hi there, thanks so much for creating this tool. 

However, as I do not have knowledge on python, I have tried and unsuccessful on using the tool.

My Python version is already 3.6+, and I am receiving below error message when Run pip install -r requirements.txt:

ERROR: Command errored out with exit status 1:
     command: 'c:\users\USER\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-ys4oaq2q\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-ys4oaq2q\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-ng2cbzln'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-ys4oaq2q\pycryptodome\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-ys4oaq2q\pycryptodome\setup.py", line 448, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\USER\AppData\Local\Temp\pip-install-ys4oaq2q\pycryptodome\compiler_opt.py", line 304, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\USER\AppData\Local\Temp\pip-install-ys4oaq2q\pycryptodome\compiler_opt.py", line 239, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\USER\AppData\Local\Temp\pip-install-ys4oaq2q\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\users\USER\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\USER\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Really looking forward to your help. Thank you!

**Comment by kmjennison** [comment]
I see this in the error logs:
`
Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
`

Have you tried that?

**Comment by u5194321** [comment]
![sc](https://user-images.githubusercontent.com/64894146/81657362-68910480-946a-11ea-9237-bf0bf7bf3683.PNG)

Thanks for your reply! it looks like i have installed C++, confirmed version above 14.0, but it's still appearing.

I'm more worried about the process before this, because I have no understanding of python. I just simply downloaded your github package, uncompress, and tried to run requirements.txt directly. I'm not sure if the above is correct. Thank you,

**Comment by kmjennison** [comment]
I'm not able to prioritize debugging, unfortunately. I'll leave this issue open in case others can help out.

**Comment by u5194321** [comment]
![image](https://user-images.githubusercontent.com/64894146/81801042-600dfc00-9546-11ea-83c4-1e126b4fea67.png)
Thanks a lot for your help, i'm able to make some progess today.
However, as seen in the sc above, the placement name is already exact match in DFP.. may I know if there are similar issue previously?

Thanks again!!

**Comment by u5194321** [comment]
![image](https://user-images.githubusercontent.com/64894146/81801683-62248a80-9547-11ea-878a-d63682f893f9.png)

Thanks a lot for your help, i'm able to make some progess today.
However, as seen in the sc above, the placement name is already exact match in DFP.. may I know if there are similar issue previously?

Thanks again!!

**Comment by kmjennison** [comment]
Glad to hear you're working through it.

No, I haven't seen this issue. Make sure you're looking at placements, not ad units, using the "name" column here:
https://admanager.google.com/[your-id-here]#inventory/placement/list

If you have multiple Ad Manager accounts, be sure you're calling the correct one. You can check that by fetching the orders: `python -m dfp.get_orders`

If that's not working, please also try it with a new placement named something simple, like "test".

**Comment by u5194321** [comment]
Thanks again.

Confirm that I am targeting the exact naming on placement, and I can successfully pull my existing orders from DFP.

I have also created a "test" placement, but still failed to be found.

May I know if there are further methods / areas I should be checking? I have asked someone else to use the exact same settings.py and they are able to successfully find my placement.

current error log:
Found user with the given email address.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\dfp-prebid-setup\tasks\add_new_prebid_partner.py", line 358, in <module>
    main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\dfp-prebid-setup\tasks\add_new_prebid_partner.py", line 355, in main
    setup_partner(user_email, advertiser_name, order_name, placements, ad_units, sizes, bidder_code, prices, num_creatives, currency_code, line_item_format)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\dfp-prebid-setup\tasks\add_new_prebid_partner.py", line 62, in setup_partner
    placement_ids = dfp.get_placements.get_placement_ids_by_name(placements)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\dfp-prebid-setup\dfp\get_placements.py", line 69, in get_placement_ids_by_name
    placement_ids.append(get_placement_by_name(placement_name)['id'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\dfp-prebid-setup\dfp\get_placements.py", line 51, in get_placement_by_name
    raise DFPObjectNotFound('No DFP placement found with name {0}'.format(
dfp.exceptions.DFPObjectNotFound: No DFP placement found with name Desktop/Mobile-ROS-OutStream1
